version = 0.1
[default.deploy.parameters]
stack_name = "serverless-rds-cluster"
resolve_s3 = true
s3_prefix = "serverless-rds-cluster"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
