AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless RDS Automation - SAM Template

Globals:
  Function:
    Timeout: 10
    Runtime: python3.11

Resources:

  CreateRDSRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: app.lambda_handler
      Events:
        ApiTrigger:
          Type: Api
          Properties:
            Path: /rds-request
            Method: POST
      Environment:
        Variables:
          QUEUE_URL: !GetAtt RDSRequestQueue.QueueUrl
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt RDSRequestQueue.QueueName

  ProcessRDSRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/
      Handler: handler.lambda_handler
      Runtime: python3.11
      Events:
        SQSTrigger:
          Type: SQS
          Properties:
            Queue: !GetAtt RDSRequestQueue.Arn
      Environment:
        Variables:
          GITHUB_TOKEN: "REPLACE_ME_IN_DEPLOYMENT"
          SECRET_ARN: "arn:aws:secretsmanager:eu-north-1:110626036047:secret:rds/credentials-ktNm2s"
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt RDSRequestQueue.QueueName
        - Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: "arn:aws:secretsmanager:eu-north-1:110626036047:secret:rds/credentials-ktNm2s"

  RDSRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: rds-request-queue

Outputs:

  ApiUrl:
    Description: "API Gateway endpoint"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/rds-request"

  RDSQueueURL:
    Description: "URL of the request queue"
    Value: !Ref RDSRequestQueue