version: 2.1

executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.6.6
    working_directory: ~/project

jobs:
  deploy:
    executor: terraform-executor
    steps:
      - checkout

      - run:
          name: Navigate to Terraform Directory
          command: cd serverless_rds_cluster/terraform

      - run:
          name: Debug - Show Terraform Files
          command: |
            cd serverless_rds_cluster/terraform
            ls -la

      - run:
          name: Initialize Terraform
          command: |
            cd serverless_rds_cluster/terraform
            terraform init

      - run:
          name: Apply Terraform using tfvars
          command: |
            cd serverless_rds_cluster/terraform
            terraform apply -auto-approve -var-file="terraform.tfvars"

workflows:
  deploy_workflow:
    jobs:
      - deploy